#!/usr/bin/env python
# coding: utf-8

import os
import shutil
import random


def get_xyz(lines, poscar,idx):
    write_poscar = open(poscar, 'w')
    write_poscar.write(lines[0])
    write_poscar.write("frame index %d\n" %idx)
    for i in range(2,len(lines)):   
        write_poscar.write(lines[i])      
    
    write_poscar.close()


def mkdir(path):
    path=path.strip()
    path=path.rstrip("\\")
    isExists=os.path.exists(path)
    if not isExists:
        os.makedirs(path) 

if __name__ == '__main__':

    xyz_path = "/data/HOME_BACKUP/pengchao/Oil/deepks/m062x_dataset/2c10h22_44h2o/024"
    xyz = "/data/HOME_BACKUP/pengchao/Oil/cp2k/c10h22/opes_expanded/124_44h2o_ion"
    xyzfile = os.path.join(xyz,"c10h22-pos-1000.xyz")
    searchfile = open(xyzfile, "r")
    lines = searchfile.readlines()
    searchfile.close() 
    
    atoms = int(lines[0].split()[0])
    s_index = 0
    s_list = []
    for line in lines:
        s_index += 1
        if 'generated by VMD' in line:
            s_list.append(s_index)
    
    j = 1
    #for i in range(801,len(s_list),5):
    for i in range(1,len(s_list),2):
    #for i in range(0,10,1):
        name = str(10000+j)
        j += 1
        mkpath = os.path.join(xyz_path, name)
        mkdir(mkpath)
        poscar = os.path.join(mkpath, 'POSCAR1.xyz') 
        get_xyz(lines[s_list[i]-2:s_list[i]+atoms], poscar, i)     
